version: '3.3'

networks:
  edv-net:

services:
  edv-database:
    image: infoabio/edv-db:beta
    container_name: edv-db
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      edv-net:
        aliases:
          - edv-db
    env_file:
      - edv.env

  edv-web:
    image: infoabio/edv-web:beta
    container_name: edv-web
    depends_on:
      - "edv-database"
    networks:
      - edv-net
    ports:
      - "80:80"
      - "443:443"
    links:
      - edv-database
    restart: always
