version: '3.3'

networks:
  edv-net:

services:
  edv-database:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      - edv-net
    environment:
      MYSQL_ROOT_PASSWORD: contrasenya_admin
      MYSQL_DATABASE: nom_base_de_dades
      MYSQL_USER: nom_usuari
      MYSQL_PASSWORD: contrasenya_usuari

  edv-web:
    build: ./php-apache
    depends_on:
      - "edv-database"
    networks:
      - edv-net
    ports:
      - "80:80"
    links:
      - edv-database
    restart: always
    volumes:
      - ./edv:/var/www/html
      - ./apache2_files:/etc/apache2
