version: '3.3'

networks:
  edv-net:

services:
  edv-database:
    image: mariadb:latest
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    networks:
      edv-net:
        aliases:
          - edv-db
    env_file:
      - edv.env

  edv-web:
    build: ./php-apache
    depends_on:
      - "edv-database"
    networks:
      - edv-net
    ports:
      - "80:80"
      - "443:443"
    links:
      - edv-database
    restart: always
    volumes:
      - ./edv:/var/www/html
      - ./apache2_files:/etc/apache2
